### ISSUE TITLE
Add a button at the bottom of the page linking to this repository

### ISSUE THREAD

**Issue by mithi** [mithi/hello-tiny-box#19]
<img width="1255" alt="Screen Shot 2020-09-01 at 10 24 45 PM" src="https://user-images.githubusercontent.com/1670421/91863831-1b979f00-eca2-11ea-8bc8-c705d643c50f.png">

**Comment by rohanj-02** [comment]
Can I take this issue?

**Comment by mithi** [comment]
> Can I take this issue?

Sure! Thanks!
